
package_path: "."

test_editors_lite:
  - version: 2019.3
  - version: trunk

test_editors_full:
  - version: 2019.3
  - version: trunk

publish_editors:
  - version: 2019.3

test_platforms:
  - name: win
    type: Unity::VM
    image: package-ci/win10:stable
    flavor: b1.large
  - name: mac
    type: Unity::VM::osx
    image: buildfarm/mac:stable
    flavor: m1.mac

publish_platforms:
  - name: win
    type: Unity::VM
    image: package-ci/win10:stable
    flavor: b1.large
  - name: mac
    type: Unity::VM::osx
    image: buildfarm/mac:stable
    flavor: m1.mac
