#pragma kernel CSMain
#include "Assets/Sensors/Cameras/Lidar/LidarOutputs/Shaders/Resources/Output.cginc"
//#include "Packages/com.unity.simviz/Sensors/Cameras/Lidar/LidarOutputs/Shaders/Resources/Output.cginc"

RWStructuredBuffer<float4> Result;

[numthreads(8,8,1)]
void CSMain (uint3 id : SV_GroupID)
{
    float4 polar = calculatePolar(id);
    if (polar.z != 0) // to avoid race condition error
        Result[getIndex(id)] = polar;
}
